# -*- coding: utf-8 -*-
"""BenSParX_NESTED_CV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15qqu3Td40vOxwqmTlyJ9ii2EQQgyp-7s
"""





# ============================================
# 1. IMPORTS
# ============================================
import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedGroupKFold, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.base import clone

from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

from sklearn.linear_model import LogisticRegression, Lasso
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.feature_selection import SelectFromModel, RFECV, SequentialFeatureSelector
from scipy.stats import mannwhitneyu

import warnings
warnings.filterwarnings("ignore")

# ============================================
# 2. LOAD DATA
# ============================================
df = pd.read_csv("/content/BenSParX.csv")

# Target and group
y = df['class'].values          # ✅ correct label
groups = df['id'].values        # ✅ speaker ID

# Features (drop ONLY these two)
X = df.drop(columns=['class', 'id']).values

# ============================================
# 3. FEATURE SELECTION METHODS
# ============================================

def mann_whitney_fs(X, y, alpha=0.05):
    selected = []
    for i in range(X.shape[1]):
        _, p = mannwhitneyu(X[y==0, i], X[y==1, i])
        if p < alpha:
            selected.append(i)
    return np.array(selected)


def lasso_fs(X, y):
    model = Lasso(alpha=0.01)
    model.fit(X, y)
    selector = SelectFromModel(model, prefit=True)
    return selector.get_support(indices=True)


def rfecv_fs(X, y):
    estimator = RandomForestClassifier(n_estimators=100, random_state=42)
    selector = RFECV(estimator, cv=5, scoring='accuracy', n_jobs=-1)
    selector.fit(X, y)
    return selector.get_support(indices=True)


def relief_sfs_fs(X, y):
    estimator = RandomForestClassifier(n_estimators=100, random_state=42)
    sfs = SequentialFeatureSelector(
        estimator,
        n_features_to_select="auto",
        direction="forward",
        cv=3,
        n_jobs=-1
    )
    sfs.fit(X, y)
    return sfs.get_support(indices=True)


feature_methods = {
    "MWU": mann_whitney_fs,
    "LASSO": lasso_fs,
    "RFECV": rfecv_fs,
    "Relief_SFS": relief_sfs_fs
}

# ============================================
# 4. ALL 9 CLASSIFIERS
# ============================================
models = {
    "LR": LogisticRegression(max_iter=1000),
    "DT": DecisionTreeClassifier(),
    "RF": RandomForestClassifier(),
    "SVM": SVC(probability=True),
    "KNN": KNeighborsClassifier(),
    "MLP": MLPClassifier(max_iter=500),
    "GB": GradientBoostingClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "XGB": GradientBoostingClassifier()  # placeholder (replace with XGBoost if installed)
}

# ============================================
# 5. HYPERPARAMETER SPACE (SIMPLIFIED)
# ============================================
param_spaces = {
    "RF": {"model__n_estimators": [100, 300]},
    "SVM": {"model__C": [0.1, 1, 10]},
    "KNN": {"model__n_neighbors": [3, 5, 7]},
    "MLP": {"model__hidden_layer_sizes": [(100,), (50,50)]},
    "GB": {"model__n_estimators": [100, 200]},
    "AdaBoost": {"model__n_estimators": [50, 100]},
    "LR": {"model__C": [0.1, 1, 10]},
    "DT": {"model__max_depth": [None, 10]},
    "XGB": {"model__n_estimators": [100, 200]}
}

# ============================================
# 6. NESTED GROUP CV
# ============================================
outer_cv = StratifiedGroupKFold(n_splits=10, shuffle=True, random_state=42)

# Store everything
all_results = []

# Store predictions per FS method
prediction_storage = {fs: [] for fs in feature_methods.keys()}

for fold, (train_idx, test_idx) in enumerate(outer_cv.split(X, y, groups)):

    print(f"\n🔵 Outer Fold {fold+1}")

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]
    g_train, g_test = groups[train_idx], groups[test_idx]

    inner_cv = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)

    for fs_name, fs_func in feature_methods.items():

        for model_name, base_model in models.items():

            pipe = Pipeline([
                ("scaler", StandardScaler()),
                ("model", clone(base_model))
            ])

            param_space = param_spaces[model_name]

            best_score = -np.inf
            best_features = None
            best_model = None

            # -------- INNER LOOP --------
            for inner_train_idx, val_idx in inner_cv.split(X_train, y_train, g_train):

                X_inner, X_val = X_train[inner_train_idx], X_train[val_idx]
                y_inner, y_val = y_train[inner_train_idx], y_train[val_idx]

                selected_idx = fs_func(X_inner, y_inner)
                if len(selected_idx) == 0:
                    continue

                X_inner_sel = X_inner[:, selected_idx]
                X_val_sel = X_val[:, selected_idx]

                search = RandomizedSearchCV(
                    pipe,
                    param_space,
                    n_iter=5,
                    cv=3,
                    scoring="accuracy",
                    n_jobs=-1,
                    random_state=42
                )

                search.fit(X_inner_sel, y_inner)

                val_pred = search.best_estimator_.predict(X_val_sel)
                score = accuracy_score(y_val, val_pred)

                if score > best_score:
                    best_score = score
                    best_features = selected_idx
                    best_model = clone(search.best_estimator_)

            # -------- TRAIN FINAL --------
            X_train_sel = X_train[:, best_features]
            X_test_sel = X_test[:, best_features]

            best_model.fit(X_train_sel, y_train)

            y_pred = best_model.predict(X_test_sel)
            y_prob = best_model.predict_proba(X_test_sel)[:, 1]

            # -------- STORE METRICS --------
            acc = accuracy_score(y_test, y_pred)
            f1 = f1_score(y_test, y_pred)
            auc = roc_auc_score(y_test, y_prob)

            all_results.append({
                "Fold": fold+1,
                "FS": fs_name,
                "Model": model_name,
                "Accuracy": acc,
                "F1": f1,
                "AUC": auc
            })

            # -------- STORE PREDICTIONS --------
            for i in range(len(y_test)):
                prediction_storage[fs_name].append({
                    "Fold": fold+1,
                    "Model": model_name,
                    "Subject_ID": g_test[i],
                    "Actual": y_test[i],
                    "Predicted": y_pred[i],
                    "Probability": y_prob[i]
                })


# ============================================
# 7. SAVE RESULTS
# ============================================

# Overall results
results_df = pd.DataFrame(all_results)
results_df.to_csv("final_metrics.csv", index=False)

# Fold-wise predictions per FS method
for fs_name, data in prediction_storage.items():
    pd.DataFrame(data).to_csv(f"predictions_{fs_name}.csv", index=False)


# ============================================
# 8. SUMMARY
# ============================================
print("\n📊 FINAL MEAN PERFORMANCE:")
print(results_df.groupby(["FS", "Model"]).mean().sort_values(by="Accuracy", ascending=False))

# ============================================
# 1. IMPORTS
# ============================================
import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedGroupKFold, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.base import clone

from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

from sklearn.linear_model import LogisticRegression, Lasso
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.feature_selection import SelectFromModel, RFECV, SequentialFeatureSelector
from scipy.stats import mannwhitneyu

import warnings
warnings.filterwarnings("ignore")

# ============================================
# 2. LOAD DATA
# ============================================
df = pd.read_csv("/content/BenSParX.csv")

y = df['class'].values
groups = df['id'].values
X = df.drop(columns=['class', 'id']).values

# ============================================
# 3. FEATURE SELECTION METHODS
# ============================================

def mann_whitney_fs(X, y, alpha=0.05):
    selected = []
    for i in range(X.shape[1]):
        _, p = mannwhitneyu(X[y==0, i], X[y==1, i])
        if p < alpha:
            selected.append(i)
    return np.array(selected)


def lasso_fs(X, y):
    model = Lasso(alpha=0.01)
    model.fit(X, y)
    selector = SelectFromModel(model, prefit=True)
    return selector.get_support(indices=True)


def rfecv_fs(X, y, model):
    selector = RFECV(
        estimator=clone(model),
        cv=3,
        scoring='accuracy',
        n_jobs=-1
    )
    selector.fit(X, y)
    return selector.get_support(indices=True)


def relief_sfs_fs(X, y):
    estimator = RandomForestClassifier(n_estimators=100, random_state=42)
    sfs = SequentialFeatureSelector(
        estimator,
        n_features_to_select="auto",
        direction="forward",
        cv=3,
        n_jobs=-1
    )
    sfs.fit(X, y)
    return sfs.get_support(indices=True)


feature_methods = {
    "MWU": mann_whitney_fs,
    "LASSO": lasso_fs,
    "RFECV": rfecv_fs,
    "Relief_SFS": relief_sfs_fs
}

# ============================================
# 4. MODELS
# ============================================
models = {
    "LR": LogisticRegression(max_iter=1000),
    "DT": DecisionTreeClassifier(),
    "RF": RandomForestClassifier(),
    "SVM": SVC(probability=True),
    "KNN": KNeighborsClassifier(),
    "MLP": MLPClassifier(max_iter=500),
    "GB": GradientBoostingClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "XGB": GradientBoostingClassifier()  # replace if XGBoost installed
}

# ============================================
# 5. PARAMETER SPACE
# ============================================
param_spaces = {
    "RF": {"model__n_estimators": [100, 300]},
    "SVM": {"model__C": [0.1, 1, 10]},
    "KNN": {"model__n_neighbors": [3, 5, 7]},
    "MLP": {"model__hidden_layer_sizes": [(100,), (50,50)]},
    "GB": {"model__n_estimators": [100, 200]},
    "AdaBoost": {"model__n_estimators": [50, 100]},
    "LR": {"model__C": [0.1, 1, 10]},
    "DT": {"model__max_depth": [None, 10]},
    "XGB": {"model__n_estimators": [100, 200]}
}

# ============================================
# 6. NESTED CV
# ============================================
outer_cv = StratifiedGroupKFold(n_splits=10, shuffle=True, random_state=42)

all_results = []
prediction_storage = {fs: [] for fs in feature_methods.keys()}

for fold, (train_idx, test_idx) in enumerate(outer_cv.split(X, y, groups)):

    print(f"\n🔵 Outer Fold {fold+1}")

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]
    g_train, g_test = groups[train_idx], groups[test_idx]

    inner_cv = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)

    for fs_name, fs_func in feature_methods.items():

        for model_name, base_model in models.items():

            pipe = Pipeline([
                ("scaler", StandardScaler()),
                ("model", clone(base_model))
            ])

            param_space = param_spaces[model_name]

            best_score = -np.inf
            best_features = None
            best_model = None

            # -------- INNER LOOP --------
            for inner_train_idx, val_idx in inner_cv.split(X_train, y_train, g_train):

                X_inner, X_val = X_train[inner_train_idx], X_train[val_idx]
                y_inner, y_val = y_train[inner_train_idx], y_train[val_idx]

                # --- Feature Selection ---
                if fs_name == "RFECV":
                    selected_idx = fs_func(X_inner, y_inner, base_model)
                else:
                    selected_idx = fs_func(X_inner, y_inner)

                if selected_idx is None or len(selected_idx) == 0:
                    continue

                X_inner_sel = X_inner[:, selected_idx]
                X_val_sel = X_val[:, selected_idx]

                search = RandomizedSearchCV(
                    pipe,
                    param_space,
                    n_iter=5,
                    cv=3,
                    scoring="accuracy",
                    n_jobs=-1,
                    random_state=42
                )

                search.fit(X_inner_sel, y_inner)

                val_pred = search.best_estimator_.predict(X_val_sel)
                score = accuracy_score(y_val, val_pred)

                if score > best_score:
                    best_score = score
                    best_features = selected_idx
                    best_model = clone(search.best_estimator_)

            # -------- SAFETY CHECK --------
            if best_features is None:
                print(f"⚠️ Skipped {fs_name}-{model_name} (no features selected)")
                continue

            # -------- FINAL TRAIN --------
            X_train_sel = X_train[:, best_features]
            X_test_sel = X_test[:, best_features]

            best_model.fit(X_train_sel, y_train)

            y_pred = best_model.predict(X_test_sel)

            # handle models without predict_proba
            if hasattr(best_model, "predict_proba"):
                y_prob = best_model.predict_proba(X_test_sel)[:, 1]
            else:
                y_prob = y_pred

            # -------- METRICS --------
            acc = accuracy_score(y_test, y_pred)
            f1 = f1_score(y_test, y_pred)
            auc = roc_auc_score(y_test, y_prob)

            all_results.append({
                "Fold": fold+1,
                "FS": fs_name,
                "Model": model_name,
                "Accuracy": acc,
                "F1": f1,
                "AUC": auc
            })

            # -------- STORE PREDICTIONS --------
            for i in range(len(y_test)):
                prediction_storage[fs_name].append({
                    "Fold": fold+1,
                    "Model": model_name,
                    "Subject_ID": g_test[i],
                    "Actual": y_test[i],
                    "Predicted": y_pred[i],
                    "Probability": y_prob[i]
                })

# ============================================
# 7. SAVE RESULTS
# ============================================
results_df = pd.DataFrame(all_results)
results_df.to_csv("final_metrics.csv", index=False)

for fs_name, data in prediction_storage.items():
    pd.DataFrame(data).to_csv(f"predictions_{fs_name}.csv", index=False)

# ============================================
# 8. SUMMARY
# ============================================
print("\n📊 FINAL MEAN PERFORMANCE:")
summary = results_df.groupby(["FS", "Model"]).mean().sort_values(by="Accuracy", ascending=False)
print(summary)

